vmware-tanzu/cartographer-conventions

.github/workflows/ci.yaml
We can use this job as a pre-req for merging PRs
Signed-off-by: Scott Andrews <andrewssc@vmware.com>
=> Aggregate the CI test results into a single job

go.mod, go.sum, go.work.sum
Signed-off-by: Scott Andrews <andrewssc@vmware.com>
=> Fix CVE-2022-21698

.gitattributes, .github/workflows/ci.yaml, codecov.yml
Signed-off-by: Scott Andrews <andrewssc@vmware.com>
=> Report test coverage with codecov

docs/design.md
Add notes on options available for priority levels for `ClusterPodConventions`
Builds on #14
=> [docs] Include notes on priority levels

.github/workflows/ci.yaml
Add v1.24 to the test matrix so we can test against this version.
=> include version 1.24 to test matrix

CHANGELOG.md
update changelog in readiness for v0.2.0 release
=> update changelog 

.ko.yaml
Signed-off-by: Rashed Kamal <krashed@vmware.com>
Pull request
Updating base image to paketobuildpacks/run-jammy-tiny:latest. Buildpacks will be deprecating the Bionic stack and introducing the Jammy stack.
Fixes #244
=> Update base image to paketobuildpacks/run-jammy-tiny:latest

.github/workflows/ci.yaml, .ko.yaml, cmd/manager/main.go, pkg/apis/thirdparty/cert-manager/v1/types.go, pkg/controllers/podintent_reconciler.go
Signed-off-by: Rashed Kamal <krashed@vmware.com>
Pull request
Updates base image and watches secret metadata only (v0.2.x only)
Fixes #
=> Updates base image and watches secret metadata only (v0.2.x only)

CHANGELOG.md
- Update changelog to include changes to be included in the v0.2.2 release. 
Creating v0.2.2 release.
=> update changelog to include v0.2.2 changes

.github/workflows/update.yaml
Signed-off-by: Rashed Kamal <krashed@vmware.com>
Pull request
Uses a SA Token when creating a pull request to update the base image.
Fixes #
=> SA Token used for base image update PR

.ko.yaml
=> update base image

.github/workflows/ci.yaml
Fix: `Repository not found: vmware-tanzu/carvel-setup-action`  
See: https://app.slack.com/client/T09NY5SBT/CH8KCCKA5
=> update action reference

.github/workflows/ci.yaml
- update carvel github actions due to repository migration
=> update carvel github action

.github/workflows/ci.yaml, Makefile, woke/woke.yaml
Reference woke rules from file.
=> reference woke rules from file

updatecli.d/ko.yaml
Pull request
Fixed base Image update template modified to support latest update-cli
Fixes #508
=> Base Image update template modified to support latest update-cli

.github/dependabot.yml
Pull request
Update setting for grouped dependencies
Fixes #
=> Update setting for grouped dependencies

hack/go.mod, samples/convention-server/go.mod, samples/dumper-server/go.mod, samples/spring-convention-server/go.mod, webhook/go.mod, webhook/hack/go.mod
Pull request
GO version for samples, webhook and hack were different for no apparent reason. Synchronizing GO version for this project.
Fixes #
=> Setting GO version to 1.20

config/manager/manager.yaml, dist/cartographer-conventions.yaml
Pull request
Extend memory limit to support processing large image and it's metadata S
Fixes #639
=> Extend memory limit

samples/spring-convention-server/README.md
Pull request
Updating docs with working and referenced sample.  
Fixes #622
=> chore: Update docs with working sample

.github/workflows/ci.yaml, README.md, config/default/kustomization.yaml, config/manager/manager.yaml, dist/bundle.values.yaml, dist/bundle.yaml, dist/cartographer-conventions.yaml, dist/package-install.values.yaml, dist/package.yaml, dist/sa-arn-annotation-overlay.yaml
Pull request
Decouple Conventions from Cartographer, use conventions-system namespace
Fixes #655
=> Decouple Conventions from Cartographer, use conventions-system namespace

dist/schema.yaml
Pull request
The default value schema is used when building the bundle pkg via `kctrl`. It generates the configurable value fields under `valueSchema` in the Package resource.
Fixes #
=> Default value schema added. This is needed to gen the OpenAPIv3 Schema in the Package resource

dist/resource-overlay.yaml, dist/schema.yaml
Pull request
Added Package CR with Resource Limit configuration
Fixes #
=> Added Package CR with Resource Limit configuration

hack/go.mod, hack/go.sum
Pull request
Bump YTT version
Fixes #
=> Bump YTT version

.github/workflows/ci.yaml, webhook/hack/go.mod
Pull request
Bump k8s versions used for CI testing
Fixes #
=> Bump k8s versions

.github/workflows/ci.yaml
=> Validate with k8s 1.33 in test matrix
